routes/web.php
<?php

use App\Task;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $request) {
    $task = new Task;

    if (!empty($request->search)) {
        $search = $request->search;
        $task->where(function ($q) use ($search) {
            $q->orWhere(
                'title',
                'like',
                "%{$search}%"
            )->orWhere(
                'description',
                'like',
                "%{$search}%"
            );
        })->get();
    } else {
        $search = '';
    }

    $pending = $task->where('status', 'pending')->get();
    $inProgress = $task->where('status', 'in-progress')->get();
    $finished = $task->where('status', 'finished')->get();

    return view('site', compact('pending', 'inProgress', 'finished', 'search'));
})->name('site');

Route::get('/task/{id}/{title?}', function ($id) {
    $task = Task::find($id);

    if ($task) {
        return view('task', compact('task'));
    }
    
    return redirect()->route('site');
})->name('task');

Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin')->middleware('can:isExecutor');

Route::middleware([ 'auth' ])->prefix('admin')->namespace('Admin')->group(function () {
    
    Route::resource('tasks', 'TaskController')->middleware('can:isExecutor');
    Route::resource('users', 'UserController')->middleware('can:isAdmin');
    Route::resource('executors', 'ExecutorController')->middleware('can:isAdmin');
    Route::resource('admins', 'AdminController')->middleware('can:isAdmin');
});

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')
<vue-page size="10">
    <vue-panel title="Dashboard">
        <vue-breadcrumbs :links="{{$breadcrumbs}}"></vue-breadcrumbs>

        <div class="row">
            @can('isExecutor')
                <div class="col-md-4">
                    <vue-box amount="{{ $totals['tasks'] }}" title="Tasks" url="{{ route('tasks.index') }}" color="orange" icon="ion ion-pie-graph"></vue-box>
                </div>
            @endcan
            
            @can('isAdmin')
                <div class="col-md-4">
                    <vue-box amount="{{ $totals['users'] }}" title="Users" url="{{ route('users.index') }}" color="blue" icon="ion ion-person-stalker"></vue-box>
                </div>
                
                <div class="col-md-4">
                    <vue-box amount="{{ $totals['executors'] }}" title="Executors" url="{{ route('executors.index') }}" color="red" icon="ion ion-person"></vue-box>
                </div>
                
                <div class="col-md-4">
                    <vue-box amount="{{ $totals['admins'] }}" title="Admins" url="{{ route('admins.index') }}" color="green" icon="ion ion-person"></vue-box>
                </div>
            @endcan
        </div>
    </vue-panel>
</vue-page>
@endsection

resources/views/site.blade.php
@extends('layouts.app')

@section('content')
<vue-page size="12">
    <vue-panel title="Tasks">

        <p>
            <form action="{{ route('site') }}" class="form-inline text-center" method="get">
                <input type="search" class="form-control" name="search" placeholder="Search..." value="{{ empty($search) ? '' : $search }}">
                <button class="btn btn-info">Search</button>
            </form>
        </p>

        <div class="row">
            <div class="col-md-4">
                <vue-panel title="Pending">
                    <div class="row">
                        @foreach ($pending as $task)
                            <vue-task-card
                                link="{{ route('task', [ $task->id, str_slug($task->title) ]) }}"
                                ending-date="{{ $task->ending_date }}"
                                executors="{{ $task->executors }}"
                                title="{{ str_limit($task->title, 25, '...') }}"
                                description="{{ str_limit($task->description, 40, '...') }}">
                            </vue-task-card>
                        @endforeach
                    </div>
                </vue-panel>
            </div>

            <div class="col-md-4">
                <vue-panel title="In Progress">
                    <div class="row">
                        @foreach ($inProgress as $task)
                            <vue-task-card
                                link="{{ route('task', [ $task->id, str_slug($task->title) ]) }}"
                                ending-date="{{ $task->ending_date }}"
                                executors="{{ $task->executors }}"
                                title="{{ str_limit($task->title, 25, '...') }}"
                                description="{{ str_limit($task->description, 40, '...') }}">
                            </vue-task-card>
                        @endforeach
                    </div>
                </vue-panel>
            </div>

            <div class="col-md-4">
                <vue-panel title="Finished">
                    <div class="row">
                        @foreach ($finished as $task)
                            <vue-task-card
                                link="{{ route('task', [ $task->id, str_slug($task->title) ]) }}"
                                ending-date="{{ $task->ending_date }}"
                                executors="{{ $task->executors }}"
                                title="{{ str_limit($task->title, 25, '...') }}"
                                description="{{ str_limit($task->description, 40, '...') }}">
                            </vue-task-card>
                        @endforeach
                    </div>
                </vue-panel>
            </div>
        </div>
    </vue-panel>
</vue-page>
@endsection

resources/views/task.blade.php
@extends('layouts.app')

@section('content')
<vue-page size="12">
    <vue-panel>
        <h2 align="center">{{ $task->title }}</h2>

        <h4 align="center">{{ $task->description }}</h4>

        <p>
            {!! $task->content !!}
        </p>

        <p align="center">
            <small>Executors: {{ $task->exedcutors }} - {{ date('d/m/Y', strtotime($task->publish_datetime)) }}</small>
        </p>
    </vue-panel>
</vue-page>
@endsection