routes/web.php
<?php

use App\Task;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $request) {
    $task = new Task;

    if (!empty($request->search)) {
        $search = $request->search;
        $task->where(function ($q) use ($search) {
            $q->orWhere(
                'title',
                'like',
                "%{$search}%"
            )->orWhere(
                'description',
                'like',
                "%{$search}%"
            );
        })->get();
    } else {
        $search = '';
    }

    $pending = $task->where('status', 'pending')->get();
    $inProgress = $task->where('status', 'in-progress')->get();
    $finished = $task->where('status', 'finished')->get();

    return view('site', compact('pending', 'inProgress', 'finished', 'search'));
})->name('site');

Route::get('/task/{id}/{title?}', function ($id) {
    $task = Task::find($id);

    if ($task) {
        return view('task', compact('task'));
    }
    
    return redirect()->route('site');
})->name('task');

Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin')->middleware('can:isExecutor');

Route::middleware([ 'auth' ])->prefix('admin')->namespace('Admin')->group(function () {
    
    Route::resource('tasks', 'TaskController')->middleware('can:isExecutor');
    Route::resource('users', 'UserController')->middleware('can:isAdmin');
    Route::resource('executors', 'ExecutorController')->middleware('can:isAdmin');
    Route::resource('admins', 'AdminController')->middleware('can:isAdmin');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Task;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function tasks()
    {
        return $this->belongsToMany(Task::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breadcrumbs = json_encode([
            [
                'title' => 'Admin',
                'url' => route('admin')
            ],
            [
                'title' => 'Users',
                'url' => ''
            ]
        ]);

        $list = User::select('id', 'name', 'email')->paginate(5);

        return view('admin.users.index', compact('breadcrumbs', 'list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $attributes = $request->all();

        $validate = \Validator::make($attributes, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'role' => 'required|string',
            'password' => 'required|string|min:6',
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withErrors($validate)->withInput();
        }

        $attributes['password'] = bcrypt($attributes['password']);

        User::create($attributes);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return User::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $attributes = $request->all();

        if (!empty($attributes['password'])) {
            $validate = \Validator::make($attributes, [
                'name' => 'required|string|max:255',
                'email' => [
                    'required',
                    'string',
                    'email',
                    'max:255',
                    Rule::unique('users')->ignore($id),
                ],
                'password' => 'required|string|min:6',
            ]);
            
            $attributes['password'] = bcrypt($attributes['password']);
        } else {
            $validate = \Validator::make($attributes, [
                'name' => 'required|string|max:255',
                'email' => [
                    'required',
                    'string',
                    'email',
                    'max:255',
                    Rule::unique('users')->ignore($id),
                ],
            ]);

            unset($attributes['password']);
        }


        if ($validate->fails()) {
            return redirect()->back()->withErrors($validate)->withInput();
        }

        User::find($id)->update($attributes);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();

        return redirect()->back();
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
<vue-page size="12">
    @if ($errors->all())
        <div class="alert alert-danger alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            @foreach ($errors->all() as $error)
                <p><strong>{{ $error }}</strong></p>
            @endforeach
        </div>
    @endif

    <vue-panel title="User List">
        <vue-breadcrumbs :links="{{$breadcrumbs}}"></vue-breadcrumbs>
        
        <vue-list-table
            :titles="[ '#', 'Name', 'e-mail' ]"
            :items="{{ json_encode($list) }}"
            :modal="true"
            sort="asc"
            sort-col="2"
            create-url="#create"
            show-url="/admin/users/"
            edit-url="/admin/users/"
            delete-url="/admin/users/"
            csrf-toekn="{{ csrf_token() }}">
        </vue-list-table>

        <div align="center">
            {{ $list }}
        </div>
    </vue-panel>
</vue-page>

<vue-modal-content id="createModal" title="Create">
    <vue-form id="createForm" css="" action="{{ route('users.store') }}" method="post" enctype="" csrf-token="{{ csrf_token() }}">
        <div class="form-group">
            <label for="name">Name</label>
            <input id="name" name="name" type="text" class="form-control" placeholder="Name" value="{{ old('name') }}">
        </div>
        
        <div class="form-group">
            <label for="email">e-mail</label>
            <input id="email" name="email" type="email" class="form-control" placeholder="e-mail" value="{{ old('email') }}">
        </div>

        <div class="form-group">
            <label for="role">Role</label>
            <select name="role" id="role" class="form-control">
                <option value="">Select...</option>
                <option {{ old('role') && old('role') == 'admin' ? 'selected' : '' }} value="admin">Administrator</option>
                <option {{ old('role') && old('role') == 'executor' ? 'selected' : '' }} value="executor">Executor</option>
            </select>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input id="password" name="password" type="password" class="form-control" placeholder="Password" value="{{ old('password') }}">
        </div>
    </vue-form>

    <span slot="footer">
        <button form="createForm" class="btn btn-info">Add</button>
    </span>
</vue-modal-content>

<vue-modal-content id="showModal" :title="$store.state.item.name">
    <div class="row">
        <div class="col-md-2">
            <p><b>e-mail:</b></p>
        </div>
        <div class="col-md-10">
            <p>@{{ $store.state.item.email }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <p><b>role:</b></p>
        </div>
        <div class="col-md-10">
            <p>@{{ $store.state.item.role == 'admin' ? 'Administrator' : 'Executor' }}</p>
        </div>
    </div>
</vue-modal-content>

<vue-modal-content id="editModal" title="Edit">
    <vue-form id="editForm" css="" :action="`/admin/users/${$store.state.item.id}`" method="put" enctype="" csrf-token="{{ csrf_token() }}">
        <div class="form-group">
            <label for="name">Name</label>
            <input id="name" name="name" type="text" class="form-control" v-model="$store.state.item.name" placeholder="Name">
        </div>
        
        <div class="form-group">
            <label for="email">e-mail</label>
            <input id="email" name="email" type="email" class="form-control" v-model="$store.state.item.email" placeholder="e-mail">
        </div>
        
        <div class="form-group">
            <label for="role">Role</label>
            <select name="role" id="role" class="form-control" v-model="$store.state.item.role">
                <option value="admin">Administrator</option>
                <option value="executor">Executor</option>
            </select>
        </div>
        
        <div class="form-group">
            <label for="pasword">Password</label>
            <input id="pasword" name="pasword" type="password" class="form-control">
        </div>
    </vue-form>

    <span slot="footer">
        <button form="editForm" class="btn btn-info">Update</button>
    </span>
</vue-modal-content>
@endsection