routes/web.php
<?php

use App\Task;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $request) {
    $task = new Task;

    if (!empty($request->search)) {
        $search = $request->search;
        $task->where(function ($q) use ($search) {
            $q->orWhere(
                'title',
                'like',
                "%{$search}%"
            )->orWhere(
                'description',
                'like',
                "%{$search}%"
            );
        })->get();
    } else {
        $search = '';
    }

    $pending = $task->where('status', 'pending')->get();
    $inProgress = $task->where('status', 'in-progress')->get();
    $finished = $task->where('status', 'finished')->get();

    return view('site', compact('pending', 'inProgress', 'finished', 'search'));
})->name('site');

Route::get('/task/{id}/{title?}', function ($id) {
    $task = Task::find($id);

    if ($task) {
        return view('task', compact('task'));
    }
    
    return redirect()->route('site');
})->name('task');

Auth::routes();

Route::get('/admin', 'AdminController@index')->name('admin')->middleware('can:isExecutor');

Route::middleware([ 'auth' ])->prefix('admin')->namespace('Admin')->group(function () {
    
    Route::resource('tasks', 'TaskController')->middleware('can:isExecutor');
    Route::resource('users', 'UserController')->middleware('can:isAdmin');
    Route::resource('executors', 'ExecutorController')->middleware('can:isAdmin');
    Route::resource('admins', 'AdminController')->middleware('can:isAdmin');
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Task extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'title',
        'description',
        'status',
        'ending_date'
    ];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Task;
use App\User;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breadcrumbs = json_encode([
            [
                'title' => 'Admin',
                'url' => route('admin')
            ],
            [
                'title' => 'Tasks',
                'url' => ''
            ]
        ]);

        $tasks = Task::select('id', 'title', 'description', 'status', 'ending_date')->paginate(5);
        $users = User::all();

        return view('admin.tasks.index', compact('breadcrumbs', 'tasks', 'users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $attributes = $request->all();

        $validate = \Validator::make($attributes, [
            'title' => 'required',
            'description' => 'required',
            'ending_date' => 'required',
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withErrors($validate)->withInput();
        }

        $task = Task::create($attributes);

        if (!empty($request->executors)) {
            $task->users()->sync($request->executors);
        }

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return Task::with('users')->find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $attributes = $request->all();

        $validate = \Validator::make($attributes, [
            'title' => 'required',
            'description' => 'required',
            'ending_date' => 'required',
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withErrors($validate)->withInput();
        }

        Task::find($id)->update($attributes);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Task::find($id)->delete();

        return redirect()->back();
    }
}

resources/views/admin/tasks/index.blade.php
@extends('layouts.app')

@section('content')
<vue-page size="12">
    @if ($errors->all())
        <div class="alert alert-danger alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            @foreach ($errors->all() as $error)
                <p><strong>{{ $error }}</strong></p>
            @endforeach
        </div>
    @endif

    <vue-panel title="Task List">
        <vue-breadcrumbs :links="{{$breadcrumbs}}"></vue-breadcrumbs>
        
        <vue-list-table
            :titles="[ '#', 'Title', 'Description', 'Status', 'Ending' ]"
            :items="{{ json_encode($tasks) }}"
            :modal="true"
            sort="desc"
            sort-col="0"
            create-url="#create"
            show-url="/admin/tasks/"
            edit-url="/admin/tasks/"
            delete-url="/admin/tasks/"
            csrf-toekn="{{ csrf_token() }}">
        </vue-list-table>

        <div align="center">
            {{ $tasks }}
        </div>
    </vue-panel>
</vue-page>

<vue-modal-content id="createModal" title="Create">
    <vue-form id="createForm" css="" action="{{ route('tasks.store') }}" method="post" enctype="" csrf-token="{{ csrf_token() }}">
        <div class="form-group">
            <label for="title">Title</label>
            <input id="title" name="title" type="text" class="form-control" placeholder="Title" value="{{ old('title') }}">
        </div>
        
        <div class="form-group">
            <label for="description">Description</label>
            <input id="description" name="description" type="text" class="form-control" placeholder="Description" value="{{ old('description') }}">
        </div>

        <div class="form-group">
            <label for="status">Status</label>
            <select name="status" id="status" class="form-control">
                <option {{ old('status') && old('status') == 'pending' ? 'selected' : '' }} value="pending">Pending</option>
                <option {{ old('status') && old('status') == 'in-progress' ? 'selected' : '' }} value="in-progress">In Progress</option>
                <option {{ old('status') && old('status') == 'finished' ? 'selected' : '' }} value="finished">Finished</option>
            </select>
        </div>

        <div class="form-group">
            <label for="executors">Executors</label>
            <vue-select name="executors[]" id="executors" class="" multiple :options="{{ json_encode($users) }}" :settings="{ text: name }">
                @foreach ($users as $user)
                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach
            </vue-select>
        </div>

        <div class="form-group">
            <label for="ending_date">Ending</label>
            <input id="ending_date" name="ending_date" type="date" class="form-control" value="{{ old('ending_date') }}">
        </div>
    </vue-form>

    <span slot="footer">
        <button form="createForm" class="btn btn-info">Add</button>
    </span>
</vue-modal-content>

<vue-modal-content id="showModal" :title="$store.state.item.title">
    <div class="row">
        <div class="col-md-2">
            <b>Description:</b>
        </div>
        <div class="col-md-10">
            <p>@{{$store.state.item.description}}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <b>Executors:</b>
        </div>
        <div class="col-md-10">
            <vue-list-array :array="$store.state.item.users"></vue-list-array>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <b>Status:</b>
        </div>
        <div class="col-md-10">
            <p>@{{$store.state.item.status}}</p>
        </div>
    </div>
</vue-modal-content>

<vue-modal-content id="editModal" title="Edit">
    <vue-form id="editForm" css="" :action="`/admin/tasks/${$store.state.item.id}`" method="put" enctype="" csrf-token="{{ csrf_token() }}">
        <div class="form-group">
            <label for="title">Title</label>
            <input id="title" name="title" type="text" class="form-control" v-model="$store.state.item.title" placeholder="Title">
        </div>
        
        <div class="form-group">
            <label for="description">Description</label>
            <input id="description" name="description" type="text" class="form-control" v-model="$store.state.item.description" placeholder="Description">
        </div>
        
        <div class="form-group">
            <label for="status">Status</label>
            <select name="status" id="status" class="form-control" v-model="$store.state.item.status">
                <option value="pending">Pending</option>
                <option value="in-progress">In Progress</option>
                <option value="finished">Finished</option>
            </select>
        </div>
    
        <div class="form-group">
            <label for="executors">Executors</label>
            <vue-select name="executors[]" id="executors" class="form-control" multiple style="width: 100%" v-model="$store.state.item.executors">
                @foreach ($users as $user)                    
                <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach
            </vue-select>
        </div>
    
        <div class="form-group">
            <label for="ending_date">Ending</label>
            <input id="ending_date" name="ending_date" type="date" class="form-control" v-model="$store.state.item.ending_date">
        </div>
    </vue-form>

    <span slot="footer">
        <button form="editForm" class="btn btn-info">Update</button>
    </span>
</vue-modal-content>
@endsection